"""
Send email with attachment via QQ Mail SMTP.

QQ Mail requires an "authorization code" (授权码), not your login password.
You can generate it in QQ Mail settings -> Account -> SMTP service.

Usage:
    python send_qq_email.py \
        --from 你的QQ号@qq.com \
        --auth-code xxxxxxxxxxxxxxxx \
        --to 279313120@qq.com \
        --subject "ETF Trade Basket" \
        --attachment output_etf_trade_plan/qmt_basket.csv
"""

from __future__ import annotations


# Ensure risk_parity_strategy modules are importable when running from another agent.
import sys
from pathlib import Path
_RPS_ROOT = Path(__file__).resolve().parents[2] / "risk_parity_strategy"
if str(_RPS_ROOT) not in sys.path:
    sys.path.insert(0, str(_RPS_ROOT))
import argparse
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path


def send_email(
    sender: str,
    auth_code: str,
    recipient: str,
    subject: str,
    body: str,
    attachment_path: str | None = None,
    smtp_server: str = "smtp.qq.com",
    smtp_port: int = 465,
) -> None:
    """Send an email with optional attachment through QQ Mail SMTP."""
    msg = MIMEMultipart()
    msg["From"] = sender
    msg["To"] = recipient
    msg["Subject"] = subject

    msg.attach(MIMEText(body, "plain", "utf-8"))

    if attachment_path:
        path = Path(attachment_path)
        if not path.exists():
            raise FileNotFoundError(f"Attachment not found: {attachment_path}")

        with open(path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())

        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f"attachment; filename= {path.name}",
        )
        msg.attach(part)
        print(f"Attached file: {path.name}")

    print(f"Connecting to {smtp_server}:{smtp_port} ...")
    with smtplib.SMTP_SSL(smtp_server, smtp_port) as server:
        server.login(sender, auth_code)
        server.sendmail(sender, [recipient], msg.as_string())

    print("Email sent successfully.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Send email with attachment via QQ Mail SMTP")
    parser.add_argument("--from", dest="sender", required=True, help="Sender QQ email")
    parser.add_argument("--auth-code", required=True, help="QQ Mail SMTP authorization code")
    parser.add_argument("--to", default="279313120@qq.com", help="Recipient email")
    parser.add_argument("--subject", default="ETF Trade Basket", help="Email subject")
    parser.add_argument(
        "--body",
        default="Please find the ETF trade basket attached. Generated by risk parity strategy.",
        help="Email body text",
    )
    parser.add_argument(
        "--attachment",
        default="output_etf_trade_plan/qmt_basket.csv",
        help="Path to attachment file",
    )
    args = parser.parse_args()

    send_email(
        sender=args.sender,
        auth_code=args.auth_code,
        recipient=args.to,
        subject=args.subject,
        body=args.body,
        attachment_path=args.attachment,
    )


if __name__ == "__main__":
    main()
