"""
Send file via Telegram Bot.

Prerequisites:
1. Create a bot in Telegram by talking to @BotFather and get a token.
2. Start a chat with your bot and get your chat_id.
   You can use @userinfobot to find your user ID, or send any message to the bot
   and visit https://api.telegram.org/bot<TOKEN>/getUpdates to get the chat_id.

Configuration priority:
1. Command line arguments (--token, --chat-id)
2. OpenClaw config file (/root/.openclaw/openclaw.json)
3. Prompt for missing values

Usage:
    python send_telegram.py \
        --token "YOUR_BOT_TOKEN" \
        --chat-id "YOUR_CHAT_ID" \
        --file output_etf_trade_plan/qmt_basket.csv \
        --caption "ETF trade basket generated today"

    # Auto-load token/chat-id from OpenClaw config
    python send_telegram.py --file output_etf_trade_plan/qmt_basket.csv
"""

from __future__ import annotations


# Ensure risk_parity_strategy modules are importable when running from another agent.
import sys
from pathlib import Path
_RPS_ROOT = Path(__file__).resolve().parents[2] / "risk_parity_strategy"
if str(_RPS_ROOT) not in sys.path:
    sys.path.insert(0, str(_RPS_ROOT))
import argparse
import asyncio
import json
from pathlib import Path

from telegram import Bot

OPENCLAW_CONFIG_PATH = Path("/root/.openclaw/openclaw.json")


def load_openclaw_telegram_config(path: Path = OPENCLAW_CONFIG_PATH) -> tuple[str | None, str | None]:
    """Load Telegram bot token and allowed chat id from OpenClaw config."""
    if not path.exists():
        return None, None

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        channels = data.get("channels", {})
        telegram_cfg = channels.get("telegram", {})
        if not telegram_cfg.get("enabled"):
            return None, None

        token = telegram_cfg.get("botToken")
        allowed = telegram_cfg.get("allowFrom", [])
        chat_id = str(allowed[0]) if allowed else None
        return token, chat_id
    except Exception as e:
        print(f"Warning: failed to load OpenClaw config: {e}")
        return None, None


async def send_file(
    token: str,
    chat_id: str,
    file_path: str,
    caption: str,
) -> None:
    """Send a document via Telegram Bot API."""
    bot = Bot(token=token)
    print("Sending file to Telegram...")
    with open(file_path, "rb") as f:
        await bot.send_document(
            chat_id=chat_id,
            document=f,
            caption=caption,
        )
    print("File sent successfully.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Send file via Telegram Bot")
    parser.add_argument("--token", help="Telegram bot token")
    parser.add_argument("--chat-id", help="Target chat ID")
    parser.add_argument(
        "--file",
        default="output_etf_trade_plan/qmt_basket.csv",
        help="Path to file to send",
    )
    parser.add_argument(
        "--caption",
        default="ETF trade basket generated by risk parity strategy.",
        help="Caption for the file",
    )
    parser.add_argument(
        "--use-openclaw",
        action="store_true",
        default=True,
        help="Load token/chat-id from /root/.openclaw/openclaw.json if not provided",
    )
    args = parser.parse_args()

    token = args.token
    chat_id = args.chat_id

    if args.use_openclaw and (not token or not chat_id):
        oc_token, oc_chat_id = load_openclaw_telegram_config()
        token = token or oc_token
        chat_id = chat_id or oc_chat_id

    if not token:
        raise ValueError("Telegram bot token is required. Provide --token or configure OpenClaw.")
    if not chat_id:
        raise ValueError("Telegram chat ID is required. Provide --chat-id or configure OpenClaw.")

    asyncio.run(
        send_file(
            token=token,
            chat_id=chat_id,
            file_path=args.file,
            caption=args.caption,
        )
    )


if __name__ == "__main__":
    main()
